name: Android CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # 设置为 write，允许发布 releases

    env:
      ACTIONS_STEP_DEBUG: true

    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Decode keystore file
        run: |
          echo "${{ secrets.SIGNING_KEY_P12 }}" | base64 -d > signing_key.p12
        shell: bash

      - name: Set environment variables for signing
        run: |
          echo "SIGNING_STORE_PASSWORD=${{ secrets.SIGNING_STORE_PASSWORD }}" >> $GITHUB_ENV
          echo "SIGNING_KEY_ALIAS=${{ secrets.SIGNING_KEY_ALIAS }}" >> $GITHUB_ENV

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Get app info from gradle
        id: app_info
        run: |
          VERSION_NAME=$(./gradlew -q --console=plain printVersion)
          echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV
          echo "version_name=$VERSION_NAME" >> $GITHUB_OUTPUT
          
          APK_NAME=$(./gradlew -q --console=plain printName)
          echo "APK_NAME=$APK_NAME" >> $GITHUB_ENV
          echo "apk_name=$APK_NAME" >> $GITHUB_OUTPUT

      - name: Build with Gradle
        run: ./gradlew assembleDebug assembleRelease -Psigning.storeFile=signing_key.p12 -Psigning.storePassword=${{ secrets.SIGNING_STORE_PASSWORD }} -Psigning.keyAlias=${{ secrets.SIGNING_KEY_ALIAS }} -Psigning.v2SigningEnabled=true

      - name: Check if release APK exists
        run: |
          if [ ! -f "app/build/outputs/apk/release/${{ steps.app_info.outputs.apk_name }}_v${{ steps.app_info.outputs.version_name }}_release.apk" ]; then
            echo "Release APK not found!"
            exit 1
          fi
          if [ ! -f "app/build/outputs/apk/debug/${{ steps.app_info.outputs.apk_name }}_v${{ steps.app_info.outputs.version_name }}_debug.apk" ]; then
            echo "Debug APK not found!"
            exit 1
          fi

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v${{ steps.app_info.outputs.version_name }}"  # 版本号作为 tag_name
          body: |
            $(cat CHANGELOG.md)
          files: |
            app/build/outputs/apk/release/${{ steps.app_info.outputs.apk_name }}_v${{ steps.app_info.outputs.version_name }}_release.apk
            app/build/outputs/apk/debug/${{ steps.app_info.outputs.apk_name }}_v${{ steps.app_info.outputs.version_name }}_debug.apk